apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "arma3.fullname" . }}
  labels:
    {{- include "arma3.labels" . | nindent 4 }}
data:
  settings.json: |
    {{- dict "bootstrap" .Values.bootstrap "steam" (dict "branch" .Values.steam.branch) "mods" .Values.mods "server" .Values.server | toPrettyJson | nindent 4 }}
  runtime.py: |
    {{- .Files.Get "files/runtime.py" | nindent 4 }}
