apiVersion: v1
kind: Service
metadata:
  name: {{ include "arma3.fullname" . }}
  labels:
    {{- include "arma3.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if ne .Values.service.type "ClusterIP" }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
  {{- end }}
  {{- with .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ . | quote }}
  {{- end }}
  selector:
    {{- include "arma3.selectorLabels" . | nindent 4 }}
  ports:
    {{- range $i, $name := list "game" "query" "steam" "von" "battleye" }}
    - name: {{ $name }}
      protocol: UDP
      port: {{ add (int $.Values.server.port) $i }}
      targetPort: {{ $name }}
      {{- if eq $.Values.service.type "NodePort" }}
      nodePort: {{ add (int $.Values.service.nodePortBase) $i }}
      {{- end }}
    {{- end }}
